### ISSUE TITLE
🐛 [BUG]: Hovering on a Custom Edge causes jitter

### ISSUE THREAD

**Issue by harshaktg** [bcakmakoglu/vue-flow#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I have a custom edge where in I listen to 2 events -> `mouseEnter` and `mouseLeave`. 
On `mouseEnter` I set it to animate and change the color while having a custom `div` rendered on top of the edge as mentioned in the examples using `EdgeLabelRenderer`
On `mouseLeave` I reset the things which were done on mouseEnter

As you see in the attached video, when the mouse is on top of the edge it works fine. But when it is on top of the custom `div` element, it causes jitter

https://github.com/bcakmakoglu/vue-flow/assets/40317596/6cd10bc3-c669-44ea-b7eb-ea14a042636f

### Expected Behavior

Ideally this shouldn't happen. Not sure if the event is being propagated to the background or not.

**Comment by bcakmakoglu** [comment]
Can you provide a reproduction for this issue?
You can find a template here: https://codesandbox.io/p/sandbox/vue-flow-basic-gfgro4

**Comment by harshaktg** [comment]
Hey @bcakmakoglu !
I have reproduced the issue in the given sandbox. Can you please check the same?

**Comment by bcakmakoglu** [comment]
Well you need to send me a link to the sandbox 😅
What I sent you is the template which you have to fork from, you send me the link to your fork 😉

**Comment by harshaktg** [comment]
Oops sorry! Missed attaching the [link](https://codesandbox.io/p/sandbox/cold-bush-psxhdr)

Here you go @bcakmakoglu

**Comment by bcakmakoglu** [comment]
Well, this is technically no bug with Vue Flow at all.
What is happening is this:
You bind mouse-enter and mouse-leave events (that's ok) - then you show the `EdgeLabelRenderer`
But when the mouse goes to that element, *mouse-leave* will be triggered -> the label is hidden
Because the label is hidden, you are hovering the edge again -> the label is shown
and this keeps repeating itself (hence the jittering effect)

For this to work properly, you would *also* have to catch mouse-enter and mouse-leave events for the label you're using and update the edge animated property and the edge.data.isHover flag.

[Here's a working sandbox.](https://codesandbox.io/p/sandbox/cold-bush-psxhdr)
