### ISSUE TITLE
🐛 [BUG]: position attributes x & y is mandatory ?

### ISSUE THREAD

**Issue by nareshv** [bcakmakoglu/vue-flow#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Nodes without x/y attributes are not shown on the graph

### Expected Behavior

Auto calculate the x/y positions for the nodes and render

### Steps To Reproduce

create a node without x/y attribute

### Relevant log output

```shell
None
```

### Anything else?

None

**Comment by bcakmakoglu** [comment]
This is not a bug.
[Positions *are required* as you documented](https://vueflow.dev/guide/getting-started.html)

**Comment by michealroberts** [comment]
@bcakmakoglu I think the end user here was asking that when a position is not supplied, it is auto-calculated ... more dynamic and complex flow diagrams are going to be almost impossible with this library, as it stands imho.

**Comment by bcakmakoglu** [comment]
The user didn't ask for a feature request though (and Issues are only for Bug-reporting), hence this issue was closed.

More dynamic and complex flow diagrams are completely possible with this library 😉 


You can always use whatever layout algorithm you prefer like ElkJS, DagreJS, D3 Force etc. on *top* of Vue Flow.
[You can find an example using Dagre right here.](https://github.com/bcakmakoglu/vue-flow/tree/master/examples/vite/src/Layouting)

**Comment by RoderickQiu** [comment]
> The user didn't ask for a feature request though (and Issues are only for Bug-reporting), hence this issue was closed.
> 
> More dynamic and complex flow diagrams are completely possible with this library 😉
> 
> You can always use whatever layout algorithm you prefer like ElkJS, DagreJS, D3 Force etc. on _top_ of Vue Flow. [You can find an example using Dagre right here.](https://github.com/bcakmakoglu/vue-flow/tree/master/examples/vite/src/Layouting)

Thanks, but it seems that this example is not shown in the doc sadly...

**Comment by nofacer** [comment]
hope this can be added to the doc

**Comment by stlbucket** [comment]
https://vueflow.dev/examples/layout/simple.html

looks like the examples page on vue flow has been updated
