### ISSUE TITLE
🐛 [BUG]: If two nodes point to each other the labels of the edges overlapping

### ISSUE THREAD

**Issue by mwessendorf** [bcakmakoglu/vue-flow#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When connecting node A with node B and node B with node A (needed for some flows) the edges crossing and the labels overlapping. Not able to get the labels "disconnected" by edge properties.
![simple_procees](https://github.com/bcakmakoglu/vue-flow/assets/16101248/e8c686dd-f56e-48da-a3ea-78045c997d13)

### Expected Behavior

Overlapping labels on edges would rearrange to not overlap each other and always be readable.

### Steps To Reproduce

Create two nodes A and B. Add two edges: first source A and target B; second source B and target A.

**Comment by bcakmakoglu** [comment]
Alas, this is not a bug but expected to happen since both labels use the same position.
You’ll have to either use different edges with non overlapping paths or offer labels if they overlap.
There’s not a built in solution for this sorry

**Comment by mwessendorf** [comment]
> Alas, this is not a bug but expected to happen since both labels use the same position. You’ll have to either use different edges with non overlapping paths or offer labels if they overlap. There’s not a built in solution for this sorry

Understood. Thanks.

**Comment by bcakmakoglu** [comment]
Sorry I have to disappoint you about a built-in helper or sth and sorry that my response was a little short; I responded from my phone 😅.

To expand a bit on this - the default edge labels (meaning `edge.label) will always be rendered at the center position.
So if two edges follow the same path or a path that would make their centers cross, the labels will, by default, inadvertently overlap. There's really no way around it unless you modify your handles in a way that edges don't overlap/cross.

If you're using a custom edge, you can use the `EdgeLabelRenderer` to place a label as a `div` on an edge.
This `EdgeLabelRenderer` needs you to apply some styles for the label to be centered, like `transform`.
The transformation is given an X and Y position so that the label gets centered, these positions are (usually) taken from the utils like `getBezierPath` -> `const [path, centerX, centerY] = getBezierPath(params)`.
*But* in this case you have the option of just offsetting these center positions by whatever *you* deem adequate so that the labels do *not* overlap anymore.

Again, there's no built-in mechanism that would catch this overlap and reposition edges but you can build this sort of logic yourself.

**Comment by bcakmakoglu** [comment]
You can find an example of how to use the `EdgeLabelRenderer` [here](https://vueflow.dev/examples/edges/).
Just open up the file `CustomEdge.vue` and check the template :)

**Comment by mwessendorf** [comment]
@bcakmakoglu Many thanks for explanation. That helps a lot. Will dive in there again and play with the positioning =)

**Comment by Haddyshu** [comment]
@mwessendorf Hello, I have encountered the same demand as you. May I refer to your solution, please? thank you
