### ISSUE TITLE
🐛 [BUG]: <title> manual control <Handle /> graph line  confusion

### ISSUE THREAD

**Issue by AlphaYoung111** [bcakmakoglu/vue-flow#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

## basic
my task is manual control node 's intersection， when user is connecting, some node's intersection should not be show, some opposite it

## code
```vue
<Handle
     v-if="show"
      :position="Position.Left"
    />

<Handle
     v-if="show"
      :position="Position.Right"
    />
``` 
I just need left and right two intersection

## graph show
<VueFlow /> binding edges is correct, A node connect to B node， their edge's handle direction is also correct.

when i am not hovering on A or B ,  the line between A and B is not from left to right, but is  from top to bottom

when i hovering on A or B, the line show correct, and the line is connect from A's right to B's left

### Expected Behavior

i hope, user don't need to hover the node ,and the edge connect direction is show correctlty by the edges binding

### Anything else?

will the feature come: 
1. config the support line, help user to align the horizontal node and the vertical node,
2. config user move node by step distance.

**Comment by bcakmakoglu** [comment]
I'm sorry but I don't understand at all what the issue is.
There's no sandbox, no pictures, a tiny bit of code that says literally nothing besides that you're using two handles, both of which don't have a `type` property set to them (which it should). If you use two handles of the same type *you have to assign them an id!*.

Please describe the issue properly and provide a bit more context otherwise I have no idea what this is about or what's wrong - until then closed for insufficient info.
