### ISSUE TITLE
🐛 [BUG]: Cannot pan while Control key is pressed on Windows

### ISSUE THREAD

**Issue by alexgrozav** [bcakmakoglu/vue-flow#1703]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When the `Control` key is pressed to enable zooming, you cannot pan.

### Expected Behavior

You should be able to both pan and zoom. This happens only for the `Control` key. Setting it to something else, such as Space `' '`, works.

### Steps To Reproduce

1. Set `pan-activation-key-code` to `Control`.
2. Set `zoom-activation-key-code` to `Control`.
3. When the `Control` key is pressed to enable zooming, you cannot pan.

### Anything else?

Environment: Chrome, Windows

**Comment by bcakmakoglu** [comment]
What is the logic behind this?
> Set pan-activation-key-code to Control.
Set zoom-activation-key-code to Control.

If both are set to `Control`, what exactly would you expect to happen here?
You can't set both features to the same key, that's not going to work.

**Comment by alexgrozav** [comment]
Here's the logic we have:
- Default behaviour using the mouse is creating the selection rectangle
- Scroll wheel is used for panning 
- Middle mouse is used for panning
- CTRL + Scroll wheel is used for zooming
- CTRL + Click and Drag is used for panning

I would expect to be able to both zoom and pan. If the activation key is used for multiple features, all the features should be available instead of being mutually exclusive.

**Comment by bcakmakoglu** [comment]
Alas, that is not a feature that is available atm and not an actual bug.
You'll have to remap these features to separate keys for now. I'll convert this to a discussion as a feature request and see what can be done about it.
One issue I can already see with this is that Control + Click creates a Contextmenu event, which would already be an issue when trying to drag something since it would just cause a rightclick to be triggered instead of a leftclick which is necessary for panning through drag.
