### ISSUE TITLE
injection "Symbol()" not found

### ISSUE THREAD

**Issue by poerlang** [bcakmakoglu/vue-flow#6]
![image](https://user-images.githubusercontent.com/3243514/143189134-b73e8791-760b-4cca-884b-49e3e0cbdab4.png)

test in chrome 95 (64)

[tmpflow.zip](https://github.com/bcakmakoglu/vue-flow/files/7593343/tmpflow.zip)

**Comment by bcakmakoglu** [comment]
Yeah that "issue" is known to me.
It happens as the Vue Flow uses a pinia store which is provided into the context with an injection.
```typescript
const store = inject(Store, undefined)
```
On first call there is no injection to be found (which is intended) and the warning is thrown even though a default value is set. From what I know undefined is a valid default value.

I'm looking to work around it somehow, usually setting a default value should work but for whatever reason it still keeps throwing the warning.

There should be no problems with the components though, everything does work as expected so the warning can be ignored for now.

**Comment by bcakmakoglu** [comment]
I could work around the warning by removing injections completely.
That would require the flow component to have a unique ID though, otherwise it'll be a little difficult to discern which store is the correct one for which flow component.

I'll try it out and see if it actually works and if it does will probably add it to one of the next releases.

**Comment by bcakmakoglu** [comment]
turns out the issue has nothing to do with my injections and is coming from pinia which is using `Symbol()` in production mode as it's injection key and doesn't provide a default which of course ends with a warning.
I'll have to ask there if there is a solution or if this is a issue that needs fixing.
I'm leaving this issue open to track it.

**Comment by bcakmakoglu** [comment]
@poerlang 
If you're interested to know:
The Pinia dev didn't seem to interested in fixing the warning so I worked up something myself and got it fixed.
The ^3.x.x release will not be throwing any more injection warnings! 🥳

**Comment by poerlang** [comment]
@bcakmakoglu  Well done Well done
