### ISSUE TITLE
🐛 [BUG]: pan is blocked when hover a nested node

### ISSUE THREAD

**Issue by tchiotludo** [bcakmakoglu/vue-flow#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

https://user-images.githubusercontent.com/2064609/218745448-e61b8dcc-0ad3-47c1-b367-839ca9a3654c.mp4

### Expected Behavior

Source of the VueFlow: [here](https://github.com/kestra-io/kestra/blob/277cdd7c7df333bd34766d475ed8b691ce89c214/ui/src/components/graph/Topology.vue#L225)
Probably due to `:nodes-draggable="false"`?

### Steps To Reproduce

1. https://demo.kestra.io/ui/flows/edit/io.kestra.demo.flows/each-nested/topology
2. enter login & password prefilled
3. try to pan when the mouse over a nested node, don't work 
4. try to pan when the mouse is not over a nested node, it works

**Comment by bcakmakoglu** [comment]
That is somewhat expected behavior.
While your nodes might not be draggable, they are still selectable, thus they catch the mouse events and the pan will not be draggable by using the node.
So you'd have to disable pointer events on nodes altogether to get the pane to be draggable over nodes as well.

You have two options to remedy the situation:
1. set `elementsSelectable` to `false` as well (which will set pointer events to `none` when used with `nodesDraggable` as `false`)
2. Use CSS to set `pointer-events: none` on the `.vue-flow__node` class

**Comment by bcakmakoglu** [comment]
Let me know if this works for you or if an alternative solution is required :)

**Comment by tchiotludo** [comment]
perfect response and so quickly, impressive :fast_forward: 
- the `elementsSelectable` prevent my hover to highlight the node 
- the `pointer-event` solution [works](https://github.com/kestra-io/kestra/commit/2e0f9070796aec6c843a1ff55aa47c492f336784) perfectly 

THanks a lot
